import type { TemplateDef } from "../types";

/**
 * Aluminum (ألمنيوم) templates: windows, doors, kitchens, glass facades, shutters.
 * 15 distinct premium designs, codes 201-215. Layout hero/nav/services follow the
 * category rotation (offset 3); every other slot is chosen to fit the concept.
 */
export const ALUMINUM_TEMPLATES: TemplateDef[] = [
  // 201 Steel: brushed-steel industrial, diagonal sheet-edge hero, graphite bands, hot-orange weld spark, sharp corners.
  {
    code: "201",
    category: "aluminum",
    name: { ar: "الفولاذ", en: "Steel" },
    description: { ar: "أزرق فولاذي وجرافيت بقصّات مائلة ولمسة برتقالية صناعية", en: "Steel blue and graphite with diagonal cuts and an industrial orange spark" },
    tokens: {
      primary: "#3d5a73",
      primaryFg: "#ffffff",
      secondary: "#1f262e",
      secondaryFg: "#eef1f4",
      accent: "#f2822a",
      accentFg: "#1a1006",
      bg: "#f6f7f9",
      surface: "#ffffff",
      surface2: "#e9edf1",
      text: "#171c22",
      muted: "#5f6b78",
      border: "#d5dbe2",
      headingFont: "kufam",
      bodyFont: "ibmPlex",
      radius: "none",
      pattern: "lines",
      mode: "light",
      buttonStyle: "square",
      divider: "diagonal",
    },
    layout: {
      nav: "minimal",
      hero: "diagonal",
      services: "zigzag",
      about: "split",
      stats: "band",
      process: "steps",
      finished: "grid",
      beforeAfter: "slider",
      progress: "stepper",
      testimonials: "cards",
      faq: "accordion",
      cta: "band",
      contact: "split",
      footer: "columns",
    },
  },

  // 202 Glass: frosted curtain-wall airiness, translucent floating cards, cyan edge-light, big soft corners and curved dividers.
  {
    code: "202",
    category: "aluminum",
    name: { ar: "الزجاج", en: "Glass" },
    description: { ar: "واجهة زجاجية شفافة بألوان جليدية وبطاقات عائمة ناعمة", en: "Frosted glass facade feel with icy tones and soft floating cards" },
    tokens: {
      primary: "#0a7399",
      primaryFg: "#ffffff",
      secondary: "#0b2e3d",
      secondaryFg: "#e6f3f8",
      accent: "#7dd3fc",
      accentFg: "#062a3f",
      bg: "#f4f9fc",
      surface: "#ffffff",
      surface2: "#e4eff5",
      text: "#0d1f2a",
      muted: "#5b7180",
      border: "#cfe0ea",
      headingFont: "alexandria",
      bodyFont: "readex",
      radius: "xl",
      pattern: "dots",
      mode: "light",
      buttonStyle: "pill",
      divider: "curve",
    },
    layout: {
      nav: "transparent",
      hero: "cards",
      services: "carousel",
      about: "cards",
      stats: "circles",
      process: "cards",
      finished: "masonry",
      beforeAfter: "hover",
      progress: "slideshow",
      testimonials: "carousel",
      faq: "cards",
      cta: "card",
      contact: "cards",
      footer: "centered",
      order: ["hero", "services", "about", "finished", "stats", "beforeAfter", "progress", "process", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 203 Horizon: dark night skyline, charcoal surfaces, electric-blue glow buttons, hex grid, cinematic video hero.
  {
    code: "203",
    category: "aluminum",
    name: { ar: "الأفق", en: "Horizon" },
    description: { ar: "أفق المدينة ليلاً بفحمي داكن وتوهج أزرق كهربائي", en: "Night-time city skyline in deep charcoal with an electric blue glow" },
    tokens: {
      primary: "#3b82f6",
      primaryFg: "#071224",
      secondary: "#111a2b",
      secondaryFg: "#e2e8f0",
      accent: "#22d3ee",
      accentFg: "#062a33",
      bg: "#0b0f17",
      surface: "#121826",
      surface2: "#1a2234",
      text: "#e6ebf2",
      muted: "#94a3b8",
      border: "#263244",
      headingFont: "sora",
      bodyFont: "ibmPlex",
      radius: "md",
      pattern: "hex",
      mode: "dark",
      buttonStyle: "glow",
      divider: "none",
    },
    layout: {
      nav: "classic",
      hero: "video",
      services: "bento",
      about: "editorial",
      stats: "inline",
      process: "timeline",
      finished: "bento",
      beforeAfter: "slider",
      progress: "timeline",
      testimonials: "quotewall",
      faq: "twocol",
      cta: "split",
      contact: "map",
      footer: "big",
    },
  },

  // 204 Tower: Kuwait Towers editorial magazine, warm paper white, navy ink, amber highlights, serif headings and underline links.
  {
    code: "204",
    category: "aluminum",
    name: { ar: "البرج", en: "Tower" },
    description: { ar: "طابع تحريري راقٍ بورق دافئ وحبر كحلي ولمسات كهرمانية", en: "Refined editorial style on warm paper with navy ink and amber highlights" },
    tokens: {
      primary: "#14315c",
      primaryFg: "#ffffff",
      secondary: "#0a1a33",
      secondaryFg: "#f3f1ea",
      accent: "#f5b301",
      accentFg: "#1a1300",
      bg: "#fbfaf6",
      surface: "#ffffff",
      surface2: "#f1eee5",
      text: "#101b2d",
      muted: "#5d6675",
      border: "#e0ddd3",
      headingFont: "playfair",
      bodyFont: "notoNaskh",
      radius: "sm",
      pattern: "geometric",
      mode: "light",
      buttonStyle: "underline",
      divider: "none",
    },
    layout: {
      nav: "split",
      hero: "editorial",
      services: "tabs",
      about: "editorial",
      stats: "inline",
      process: "numbers",
      finished: "filmstrip",
      beforeAfter: "sidebyside",
      progress: "filmstrip",
      testimonials: "single",
      faq: "twocol",
      cta: "minimal",
      contact: "inline",
      footer: "columns",
      order: ["hero", "about", "services", "finished", "stats", "process", "beforeAfter", "progress", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 205 Gulf: Arabian Gulf waters, sea-teal primary, sand-gold accent, wave dividers, gallery hero with generous rounding.
  {
    code: "205",
    category: "aluminum",
    name: { ar: "الخليج", en: "Gulf" },
    description: { ar: "أزرق الخليج المخضرّ مع ذهب الرمال وفواصل متموجة", en: "Gulf sea teal with sandy gold and rolling wave dividers" },
    tokens: {
      primary: "#0c6f6a",
      primaryFg: "#ffffff",
      secondary: "#063a3c",
      secondaryFg: "#e6f4f3",
      accent: "#e9c46a",
      accentFg: "#2b2106",
      bg: "#fbfdfd",
      surface: "#ffffff",
      surface2: "#e6f2f1",
      text: "#0c2226",
      muted: "#52706f",
      border: "#cfe2e1",
      headingFont: "elMessiri",
      bodyFont: "tajawal",
      radius: "lg",
      pattern: "waves",
      mode: "light",
      buttonStyle: "solid",
      divider: "wave",
    },
    layout: {
      nav: "pill",
      hero: "gallery",
      services: "list",
      about: "band",
      stats: "cards",
      process: "steps",
      finished: "carousel",
      beforeAfter: "tabs",
      progress: "slideshow",
      testimonials: "carousel",
      faq: "accordion",
      cta: "band",
      contact: "map",
      footer: "big",
    },
  },

  // 206 Sail: dhow sail heritage, canvas off-white, cobalt sea, brass fittings, arched hero and arch dividers, arabesque lattice.
  {
    code: "206",
    category: "aluminum",
    name: { ar: "الشراع", en: "Sail" },
    description: { ar: "قماش الشراع وأزرق الكوبالت ونحاس أصفر بأقواس تراثية", en: "Sailcloth white, cobalt sea and brass with heritage arches" },
    tokens: {
      primary: "#1e40af",
      primaryFg: "#ffffff",
      secondary: "#101c4d",
      secondaryFg: "#eef0f8",
      accent: "#c8a24a",
      accentFg: "#1c1605",
      bg: "#fcfbf7",
      surface: "#ffffff",
      surface2: "#f2efe5",
      text: "#131a33",
      muted: "#5b6280",
      border: "#e1ded2",
      headingFont: "rakkas",
      bodyFont: "harmattan",
      radius: "full",
      pattern: "arabesque",
      mode: "light",
      buttonStyle: "pill",
      divider: "arch",
    },
    layout: {
      nav: "boxed",
      hero: "arch",
      services: "iconrow",
      about: "quote",
      stats: "circles",
      process: "numbers",
      finished: "grid",
      beforeAfter: "slider",
      progress: "stepper",
      testimonials: "single",
      faq: "cards",
      cta: "card",
      contact: "cards",
      footer: "centered",
      order: ["hero", "about", "services", "stats", "process", "finished", "beforeAfter", "progress", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 207 Marina: harbour at dusk, dark gunmetal, copper primary, sea-teal accent, outlined buttons, stacked hero.
  {
    code: "207",
    category: "aluminum",
    name: { ar: "المرسى", en: "Marina" },
    description: { ar: "رمادي معدني داكن مع نحاس دافئ وأزرق بحري هادئ", en: "Dark gunmetal with warm copper and a calm sea-teal accent" },
    tokens: {
      primary: "#c47a3a",
      primaryFg: "#1a0f06",
      secondary: "#1b2228",
      secondaryFg: "#e8ecef",
      accent: "#4fb3bf",
      accentFg: "#06272b",
      bg: "#12171b",
      surface: "#1a2126",
      surface2: "#222b31",
      text: "#e7ebee",
      muted: "#95a3ad",
      border: "#2e3a42",
      headingFont: "changa",
      bodyFont: "almarai",
      radius: "sm",
      pattern: "waves",
      mode: "dark",
      buttonStyle: "outline",
      divider: "none",
    },
    layout: {
      nav: "centered",
      hero: "stacked",
      services: "grid",
      about: "split",
      stats: "band",
      process: "timeline",
      finished: "masonry",
      beforeAfter: "hover",
      progress: "filmstrip",
      testimonials: "cards",
      faq: "accordion",
      cta: "split",
      contact: "split",
      footer: "columns",
    },
  },

  // 208 Lighthouse: black-and-white industrial, pure white and ink black, single beacon-yellow accent, zigzag dividers, split hero.
  {
    code: "208",
    category: "aluminum",
    name: { ar: "الفنار", en: "Lighthouse" },
    description: { ar: "أبيض وأسود صناعي حاد بلمسة صفراء واحدة كضوء الفنار", en: "Sharp black-and-white industrial look with a single beacon-yellow accent" },
    tokens: {
      primary: "#161616",
      primaryFg: "#ffffff",
      secondary: "#0a0a0a",
      secondaryFg: "#f5f5f5",
      accent: "#ffcc33",
      accentFg: "#1a1400",
      bg: "#ffffff",
      surface: "#f5f5f5",
      surface2: "#ebebeb",
      text: "#111111",
      muted: "#666666",
      border: "#dadada",
      headingFont: "notoKufi",
      bodyFont: "rubik",
      radius: "none",
      pattern: "stars",
      mode: "light",
      buttonStyle: "solid",
      divider: "zigzag",
    },
    layout: {
      nav: "minimal",
      hero: "split",
      services: "zigzag",
      about: "editorial",
      stats: "inline",
      process: "numbers",
      finished: "grid",
      beforeAfter: "sidebyside",
      progress: "stepper",
      testimonials: "quotewall",
      faq: "twocol",
      cta: "minimal",
      contact: "inline",
      footer: "minimal",
      order: ["hero", "services", "finished", "about", "stats", "process", "beforeAfter", "progress", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 209 Dusk: Kuwait sky at maghrib, violet primary with sunset-orange accent, fullscreen hero, glow buttons, clean unpatterned surfaces.
  {
    code: "209",
    category: "aluminum",
    name: { ar: "الغسق", en: "Dusk" },
    description: { ar: "بنفسجي الغسق مع برتقالي الغروب وواجهة بملء الشاشة", en: "Dusk violet with sunset orange and a full-screen hero" },
    tokens: {
      primary: "#5b3fa6",
      primaryFg: "#ffffff",
      secondary: "#1e1538",
      secondaryFg: "#ece8f7",
      accent: "#fb923c",
      accentFg: "#2a1200",
      bg: "#f8f7fc",
      surface: "#ffffff",
      surface2: "#eeebf7",
      text: "#1a1530",
      muted: "#675f80",
      border: "#dcd8ea",
      headingFont: "zain",
      bodyFont: "vazirmatn",
      radius: "xl",
      pattern: "none",
      mode: "light",
      buttonStyle: "glow",
      divider: "curve",
    },
    layout: {
      nav: "transparent",
      hero: "fullscreen",
      services: "carousel",
      about: "cards",
      stats: "band",
      process: "cards",
      finished: "carousel",
      beforeAfter: "slider",
      progress: "slideshow",
      testimonials: "carousel",
      faq: "accordion",
      cta: "card",
      contact: "map",
      footer: "big",
    },
  },

  // 210 Falcon: desert night, warm near-black, gold primary, burnt-orange accent, Sadu weave, Ruqaa calligraphy headings.
  {
    code: "210",
    category: "aluminum",
    name: { ar: "الصقر", en: "Falcon" },
    description: { ar: "ليل الصحراء بأسود دافئ وذهب صقري ونقوش السدو", en: "Desert night in warm black with falcon gold and Sadu weave" },
    tokens: {
      primary: "#d4a539",
      primaryFg: "#1c1505",
      secondary: "#1c1a16",
      secondaryFg: "#f1ede4",
      accent: "#c2410c",
      accentFg: "#ffffff",
      bg: "#100f0d",
      surface: "#181613",
      surface2: "#211e1a",
      text: "#f0eadd",
      muted: "#a59c8c",
      border: "#35302a",
      headingFont: "arefRuqaa",
      bodyFont: "notoNaskh",
      radius: "md",
      pattern: "sadu",
      mode: "dark",
      buttonStyle: "solid",
      divider: "none",
    },
    layout: {
      nav: "classic",
      hero: "centered",
      services: "bento",
      about: "quote",
      stats: "cards",
      process: "steps",
      finished: "bento",
      beforeAfter: "tabs",
      progress: "timeline",
      testimonials: "single",
      faq: "cards",
      cta: "band",
      contact: "cards",
      footer: "centered",
      order: ["hero", "about", "services", "finished", "progress", "beforeAfter", "stats", "process", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 211 Metal: diamond-plate workshop, slate primary, lime accent, hard corners, square buttons, diagonal hero cut.
  {
    code: "211",
    category: "aluminum",
    name: { ar: "المعدن", en: "Metal" },
    description: { ar: "رمادي أردوازي مع أخضر ليموني وزوايا حادة بطابع الورشة", en: "Slate grey with lime green and hard workshop edges" },
    tokens: {
      primary: "#334155",
      primaryFg: "#ffffff",
      secondary: "#0f172a",
      secondaryFg: "#f1f5f9",
      accent: "#a3e635",
      accentFg: "#14200a",
      bg: "#ffffff",
      surface: "#f1f5f9",
      surface2: "#e2e8f0",
      text: "#0f172a",
      muted: "#5a6678",
      border: "#cbd5e1",
      headingFont: "manrope",
      bodyFont: "almarai",
      radius: "none",
      pattern: "diamonds",
      mode: "light",
      buttonStyle: "square",
      divider: "diagonal",
    },
    layout: {
      nav: "split",
      hero: "diagonal",
      services: "tabs",
      about: "band",
      stats: "cards",
      process: "timeline",
      finished: "filmstrip",
      beforeAfter: "hover",
      progress: "filmstrip",
      testimonials: "cards",
      faq: "twocol",
      cta: "split",
      contact: "inline",
      footer: "minimal",
    },
  },

  // 212 Facade: green-tinted curtain wall, deep green primary, chrome-silver accent, mashrabiya lattice, pill nav, wave dividers.
  {
    code: "212",
    category: "aluminum",
    name: { ar: "الواجهة", en: "Facade" },
    description: { ar: "أخضر عميق مع فضي الكروم وشبك المشربية", en: "Deep green with chrome silver and mashrabiya lattice" },
    tokens: {
      primary: "#175c3b",
      primaryFg: "#ffffff",
      secondary: "#0b2e20",
      secondaryFg: "#e8f1ec",
      accent: "#c5ced6",
      accentFg: "#0f1a14",
      bg: "#f7faf8",
      surface: "#ffffff",
      surface2: "#e9f1ec",
      text: "#0e1f17",
      muted: "#5a6f65",
      border: "#d3dfd8",
      headingFont: "reemKufi",
      bodyFont: "mada",
      radius: "lg",
      pattern: "mashrabiya",
      mode: "light",
      buttonStyle: "pill",
      divider: "wave",
    },
    layout: {
      nav: "pill",
      hero: "cards",
      services: "list",
      about: "cards",
      stats: "circles",
      process: "cards",
      finished: "masonry",
      beforeAfter: "sidebyside",
      progress: "stepper",
      testimonials: "quotewall",
      faq: "accordion",
      cta: "card",
      contact: "split",
      footer: "columns",
      order: ["hero", "services", "about", "stats", "finished", "beforeAfter", "progress", "process", "testimonials", "cta", "faq", "contact"],
    },
  },

  // 213 Port: night port, graphite dark, platinum-silver primary, teal harbour lights, boxed nav, brushed-line texture.
  {
    code: "213",
    category: "aluminum",
    name: { ar: "الميناء", en: "Port" },
    description: { ar: "جرافيت ليلي مع بلاتين لامع وأضواء مرفأ فيروزية", en: "Night graphite with bright platinum and teal harbour lights" },
    tokens: {
      primary: "#cfd6dd",
      primaryFg: "#0f1418",
      secondary: "#1d2226",
      secondaryFg: "#e6eaee",
      accent: "#5eead4",
      accentFg: "#042f2e",
      bg: "#0e1113",
      surface: "#161a1d",
      surface2: "#1f2428",
      text: "#e8ecef",
      muted: "#98a2ab",
      border: "#2b3237",
      headingFont: "cairo",
      bodyFont: "notoSans",
      radius: "sm",
      pattern: "lines",
      mode: "dark",
      buttonStyle: "outline",
      divider: "none",
    },
    layout: {
      nav: "boxed",
      hero: "video",
      services: "iconrow",
      about: "editorial",
      stats: "band",
      process: "numbers",
      finished: "grid",
      beforeAfter: "slider",
      progress: "timeline",
      testimonials: "carousel",
      faq: "twocol",
      cta: "minimal",
      contact: "map",
      footer: "big",
    },
  },

  // 214 Pearl: mother-of-pearl heritage, warm pearl white, mauve nacre primary, seafoam accent, Amiri serif editorial hero, pearl-dot texture.
  {
    code: "214",
    category: "aluminum",
    name: { ar: "الدرة", en: "Pearl" },
    description: { ar: "أبيض لؤلؤي دافئ مع بنفسجي الصدف وأخضر زبد البحر", en: "Warm pearl white with nacre mauve and seafoam green" },
    tokens: {
      primary: "#7a5c6e",
      primaryFg: "#ffffff",
      secondary: "#2a2430",
      secondaryFg: "#f3eef1",
      accent: "#9fd8cf",
      accentFg: "#0f302c",
      bg: "#fdfcfa",
      surface: "#ffffff",
      surface2: "#f4f0ee",
      text: "#221c22",
      muted: "#6f6670",
      border: "#e6dfe2",
      headingFont: "amiri",
      bodyFont: "readex",
      radius: "md",
      pattern: "dots",
      mode: "light",
      buttonStyle: "underline",
      divider: "none",
    },
    layout: {
      nav: "centered",
      hero: "editorial",
      services: "grid",
      about: "quote",
      stats: "inline",
      process: "steps",
      finished: "carousel",
      beforeAfter: "tabs",
      progress: "slideshow",
      testimonials: "single",
      faq: "cards",
      cta: "minimal",
      contact: "cards",
      footer: "centered",
      order: ["hero", "about", "finished", "services", "stats", "beforeAfter", "progress", "process", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 215 Sands: desert dunes, warm sand paper, terracotta primary, oasis-teal accent, gallery hero, arch dividers, fully rounded friendly shapes.
  {
    code: "215",
    category: "aluminum",
    name: { ar: "الرمال", en: "Sands" },
    description: { ar: "رمال دافئة مع طين محروق وفيروزي الواحة بأشكال مستديرة", en: "Warm sands with terracotta and oasis teal in fully rounded shapes" },
    tokens: {
      primary: "#b5533c",
      primaryFg: "#ffffff",
      secondary: "#3a2a22",
      secondaryFg: "#f6efe7",
      accent: "#0f5e5a",
      accentFg: "#ffffff",
      bg: "#faf6ef",
      surface: "#ffffff",
      surface2: "#f1e9db",
      text: "#2a211b",
      muted: "#7a6c60",
      border: "#e4d9c8",
      headingFont: "baloo",
      bodyFont: "tajawal",
      radius: "full",
      pattern: "sadu",
      mode: "light",
      buttonStyle: "solid",
      divider: "arch",
    },
    layout: {
      nav: "minimal",
      hero: "gallery",
      services: "zigzag",
      about: "split",
      stats: "circles",
      process: "cards",
      finished: "bento",
      beforeAfter: "hover",
      progress: "stepper",
      testimonials: "cards",
      faq: "accordion",
      cta: "band",
      contact: "inline",
      footer: "minimal",
    },
  },
];
