import type { TemplateDef } from "../types";

/**
 * Ceramic (سيراميك) templates: tiles, porcelain, marble, bathrooms, kitchens and facades.
 * Codes 401-415. Layout slots hero/nav/services follow the platform rotation with category offset 9:
 *   hero = HEROES[(i + 9) % 10], nav = NAVS[(2i + 9) % 7], services = SERVICES[(3i + 9) % 7].
 */
export const CERAMIC_TEMPLATES: TemplateDef[] = [
  // 401 Marble: white Carrara slabs with copper trim, hairline veins, sharp square corners and a stacked editorial hero.
  {
    code: "401",
    category: "ceramic",
    name: { ar: "الرخام", en: "Marble" },
    description: { ar: "أبيض رخامي نقي مع لمسات نحاسية دافئة وعروق رفيعة", en: "Pure marble white with warm copper trim and hairline veins" },
    tokens: {
      primary: "#b3541e",
      primaryFg: "#ffffff",
      secondary: "#1c1917",
      secondaryFg: "#fafaf9",
      accent: "#0e7490",
      accentFg: "#ffffff",
      bg: "#fdfcfa",
      surface: "#ffffff",
      surface2: "#f4efe8",
      text: "#1c1917",
      muted: "#6b6560",
      border: "#e6dfd6",
      headingFont: "playfair",
      bodyFont: "notoSans",
      radius: "none",
      pattern: "lines",
      mode: "light",
      buttonStyle: "outline",
      divider: "none",
    },
    layout: {
      nav: "split",
      hero: "stacked",
      services: "bento",
      about: "editorial",
      stats: "inline",
      process: "numbers",
      finished: "masonry",
      beforeAfter: "slider",
      progress: "slideshow",
      testimonials: "single",
      faq: "twocol",
      cta: "minimal",
      contact: "split",
      footer: "columns",
      order: ["hero", "services", "finished", "about", "stats", "process", "beforeAfter", "progress", "testimonials", "cta", "faq", "contact"],
    },
  },

  // 402 Terracotta: sun-baked clay orange on cream, sadu weave motif, rounded pill navigation and wavy section edges.
  {
    code: "402",
    category: "ceramic",
    name: { ar: "التراكوتا", en: "Terracotta" },
    description: { ar: "طين محروق دافئ على كريمي ناعم بنقوش السدو", en: "Warm fired clay on soft cream with sadu weave accents" },
    tokens: {
      primary: "#bf4a1f",
      primaryFg: "#ffffff",
      secondary: "#3f2a1d",
      secondaryFg: "#fbf3e8",
      accent: "#e0a458",
      accentFg: "#3f2a1d",
      bg: "#fbf5ec",
      surface: "#fffaf3",
      surface2: "#f3e7d6",
      text: "#2b1d14",
      muted: "#7c6555",
      border: "#e8d8c3",
      headingFont: "changa",
      bodyFont: "tajawal",
      radius: "lg",
      pattern: "sadu",
      mode: "light",
      buttonStyle: "solid",
      divider: "wave",
    },
    layout: {
      nav: "pill",
      hero: "split",
      services: "tabs",
      about: "split",
      stats: "band",
      process: "steps",
      finished: "grid",
      beforeAfter: "sidebyside",
      progress: "timeline",
      testimonials: "cards",
      faq: "accordion",
      cta: "band",
      contact: "cards",
      footer: "big",
    },
  },

  // 403 Onyx: jet-black polished stone with gold leaf, arabesque tracery, fullscreen hero and glowing gold buttons.
  {
    code: "403",
    category: "ceramic",
    name: { ar: "الأونيكس", en: "Onyx" },
    description: { ar: "أسود أونيكس لامع مع ذهب ونقوش أرابيسك فاخرة", en: "Polished onyx black with gold and luxurious arabesque tracery" },
    tokens: {
      primary: "#d4a24c",
      primaryFg: "#15110b",
      secondary: "#1f1a14",
      secondaryFg: "#f5ead6",
      accent: "#e7d9bd",
      accentFg: "#1a1612",
      bg: "#0e0d0b",
      surface: "#171512",
      surface2: "#1f1c18",
      text: "#f3ece0",
      muted: "#a39a8b",
      border: "#2d2924",
      headingFont: "amiri",
      bodyFont: "notoNaskh",
      radius: "sm",
      pattern: "arabesque",
      mode: "dark",
      buttonStyle: "glow",
      divider: "none",
    },
    layout: {
      nav: "boxed",
      hero: "fullscreen",
      services: "list",
      about: "quote",
      stats: "circles",
      process: "timeline",
      finished: "carousel",
      beforeAfter: "hover",
      progress: "filmstrip",
      testimonials: "quotewall",
      faq: "cards",
      cta: "split",
      contact: "map",
      footer: "centered",
      order: ["hero", "finished", "services", "about", "beforeAfter", "progress", "stats", "process", "testimonials", "cta", "faq", "contact"],
    },
  },

  // 404 Zellige: Moroccan-Gulf turquoise glaze on sand, eight-point star tiles, centered composition and zigzag dividers.
  {
    code: "404",
    category: "ceramic",
    name: { ar: "الزليج", en: "Zellige" },
    description: { ar: "فيروزي مزجج على رمل دافئ بنجوم ثمانية تقليدية", en: "Glazed turquoise on warm sand with traditional eight-point stars" },
    tokens: {
      primary: "#0b7a76",
      primaryFg: "#ffffff",
      secondary: "#123f4a",
      secondaryFg: "#eaf6f4",
      accent: "#e2b04a",
      accentFg: "#1b2a2e",
      bg: "#f8f3e8",
      surface: "#fffdf8",
      surface2: "#efe6d3",
      text: "#1c2a2c",
      muted: "#5f6f70",
      border: "#ddd3bf",
      headingFont: "reemKufi",
      bodyFont: "almarai",
      radius: "md",
      pattern: "stars",
      mode: "light",
      buttonStyle: "pill",
      divider: "zigzag",
    },
    layout: {
      nav: "centered",
      hero: "centered",
      services: "iconrow",
      about: "cards",
      stats: "cards",
      process: "cards",
      finished: "bento",
      beforeAfter: "tabs",
      progress: "stepper",
      testimonials: "carousel",
      faq: "accordion",
      cta: "card",
      contact: "inline",
      footer: "minimal",
    },
  },

  // 405 Travertine: sage green on porous travertine beige, soft dotted texture, generous xl rounding and a diagonal hero cut.
  {
    code: "405",
    category: "ceramic",
    name: { ar: "الترافرتين", en: "Travertine" },
    description: { ar: "أخضر مريمي هادئ على بيج ترافرتين مسامي", en: "Calm sage green on porous travertine beige" },
    tokens: {
      primary: "#566f52",
      primaryFg: "#ffffff",
      secondary: "#2f3a2c",
      secondaryFg: "#f2f1ea",
      accent: "#c9a66b",
      accentFg: "#2a2416",
      bg: "#f6f2ea",
      surface: "#fbf9f4",
      surface2: "#ece5d8",
      text: "#26291f",
      muted: "#6c6f62",
      border: "#dcd6c8",
      headingFont: "elMessiri",
      bodyFont: "readex",
      radius: "xl",
      pattern: "dots",
      mode: "light",
      buttonStyle: "square",
      divider: "curve",
    },
    layout: {
      nav: "minimal",
      hero: "diagonal",
      services: "grid",
      about: "band",
      stats: "inline",
      process: "steps",
      finished: "filmstrip",
      beforeAfter: "slider",
      progress: "slideshow",
      testimonials: "single",
      faq: "twocol",
      cta: "minimal",
      contact: "split",
      footer: "columns",
      order: ["hero", "about", "services", "process", "finished", "beforeAfter", "progress", "stats", "faq", "testimonials", "cta", "contact"],
    },
  },

  // 406 Nacre: mother-of-pearl blush with charcoal, soft wave shimmer, fully rounded pill shapes and arched dividers.
  {
    code: "406",
    category: "ceramic",
    name: { ar: "الصدف", en: "Nacre" },
    description: { ar: "وردي صدفي ناعم مع فحمي أنيق وانحناءات لؤلؤية", en: "Soft pearl blush with elegant charcoal and pearly curves" },
    tokens: {
      primary: "#b0566a",
      primaryFg: "#ffffff",
      secondary: "#2a2628",
      secondaryFg: "#fbeff1",
      accent: "#f2c6c2",
      accentFg: "#3a2224",
      bg: "#fdf8f7",
      surface: "#ffffff",
      surface2: "#f8ecea",
      text: "#2a2628",
      muted: "#7a6d70",
      border: "#ecdcdb",
      headingFont: "marhey",
      bodyFont: "vazirmatn",
      radius: "full",
      pattern: "waves",
      mode: "light",
      buttonStyle: "pill",
      divider: "arch",
    },
    layout: {
      nav: "transparent",
      hero: "cards",
      services: "zigzag",
      about: "split",
      stats: "circles",
      process: "numbers",
      finished: "masonry",
      beforeAfter: "hover",
      progress: "stepper",
      testimonials: "cards",
      faq: "cards",
      cta: "card",
      contact: "cards",
      footer: "centered",
    },
  },

  // 407 Cobalt: Mediterranean cobalt-and-white tile with lemon gold, diamond lattice, video hero and diagonal cuts.
  {
    code: "407",
    category: "ceramic",
    name: { ar: "الكوبالت", en: "Cobalt" },
    description: { ar: "أزرق كوبالت متوسطي على أبيض ناصع بلمسة ليمونية", en: "Mediterranean cobalt on crisp white with a lemon-gold touch" },
    tokens: {
      primary: "#1f3fa8",
      primaryFg: "#ffffff",
      secondary: "#0f1f4d",
      secondaryFg: "#eef3ff",
      accent: "#f0b429",
      accentFg: "#1a1a1a",
      bg: "#ffffff",
      surface: "#f5f8ff",
      surface2: "#e9eefb",
      text: "#0f172a",
      muted: "#5b6478",
      border: "#d9e0f0",
      headingFont: "kufam",
      bodyFont: "rubik",
      radius: "sm",
      pattern: "diamonds",
      mode: "light",
      buttonStyle: "solid",
      divider: "diagonal",
    },
    layout: {
      nav: "classic",
      hero: "video",
      services: "carousel",
      about: "editorial",
      stats: "band",
      process: "timeline",
      finished: "grid",
      beforeAfter: "sidebyside",
      progress: "timeline",
      testimonials: "carousel",
      faq: "accordion",
      cta: "band",
      contact: "map",
      footer: "big",
    },
  },

  // 408 Graphite: dark graphite porcelain with rose-gold hairlines, hex tile grid, underline buttons and an editorial hero.
  {
    code: "408",
    category: "ceramic",
    name: { ar: "الجرافيت", en: "Graphite" },
    description: { ar: "جرافيت داكن مع ذهب وردي وشبكة سداسية عصرية", en: "Dark graphite with rose gold and a modern hexagonal grid" },
    tokens: {
      primary: "#c98b7a",
      primaryFg: "#1a1516",
      secondary: "#141416",
      secondaryFg: "#ece7e6",
      accent: "#e8c9b5",
      accentFg: "#1a1516",
      bg: "#17171a",
      surface: "#1f1f23",
      surface2: "#27272c",
      text: "#efeceb",
      muted: "#a09b9c",
      border: "#34343a",
      headingFont: "sora",
      bodyFont: "ibmPlex",
      radius: "none",
      pattern: "hex",
      mode: "dark",
      buttonStyle: "underline",
      divider: "none",
    },
    layout: {
      nav: "split",
      hero: "editorial",
      services: "bento",
      about: "quote",
      stats: "inline",
      process: "numbers",
      finished: "filmstrip",
      beforeAfter: "tabs",
      progress: "filmstrip",
      testimonials: "quotewall",
      faq: "twocol",
      cta: "minimal",
      contact: "inline",
      footer: "minimal",
      order: ["hero", "finished", "about", "services", "process", "stats", "beforeAfter", "progress", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 409 Emerald: deep forest green on ivory with brushed gold, Islamic geometric lattice and a gallery-style hero.
  {
    code: "409",
    category: "ceramic",
    name: { ar: "الزمرد", en: "Emerald" },
    description: { ar: "أخضر غابي عميق على عاجي مع ذهب مصقول وهندسة إسلامية", en: "Deep forest green on ivory with brushed gold and Islamic geometry" },
    tokens: {
      primary: "#1f5c45",
      primaryFg: "#ffffff",
      secondary: "#0f2e24",
      secondaryFg: "#edf5ef",
      accent: "#d1b06b",
      accentFg: "#1b2a21",
      bg: "#fbf9f2",
      surface: "#ffffff",
      surface2: "#f1eee2",
      text: "#1b2a21",
      muted: "#5f6b62",
      border: "#dfdccd",
      headingFont: "markazi",
      bodyFont: "lateef",
      radius: "md",
      pattern: "geometric",
      mode: "light",
      buttonStyle: "outline",
      divider: "curve",
    },
    layout: {
      nav: "pill",
      hero: "gallery",
      services: "tabs",
      about: "cards",
      stats: "cards",
      process: "cards",
      finished: "bento",
      beforeAfter: "slider",
      progress: "slideshow",
      testimonials: "single",
      faq: "cards",
      cta: "split",
      contact: "split",
      footer: "columns",
    },
  },

  // 410 Ruby: burgundy glaze on warm beige, mashrabiya lattice, arched hero windows and calligraphic Ruqaa headings.
  {
    code: "410",
    category: "ceramic",
    name: { ar: "الياقوت", en: "Ruby" },
    description: { ar: "عنابي غني على بيج دافئ بأقواس ومشربيات", en: "Rich burgundy on warm beige with arches and mashrabiya lattice" },
    tokens: {
      primary: "#7b1e2e",
      primaryFg: "#ffffff",
      secondary: "#2c1418",
      secondaryFg: "#f6e9e6",
      accent: "#d2b48c",
      accentFg: "#2c1418",
      bg: "#f7f1e8",
      surface: "#fdf9f3",
      surface2: "#eee3d4",
      text: "#2a1b1c",
      muted: "#74625f",
      border: "#e2d5c4",
      headingFont: "arefRuqaa",
      bodyFont: "harmattan",
      radius: "lg",
      pattern: "mashrabiya",
      mode: "light",
      buttonStyle: "solid",
      divider: "arch",
    },
    layout: {
      nav: "boxed",
      hero: "arch",
      services: "list",
      about: "band",
      stats: "circles",
      process: "steps",
      finished: "carousel",
      beforeAfter: "hover",
      progress: "stepper",
      testimonials: "cards",
      faq: "accordion",
      cta: "card",
      contact: "cards",
      footer: "centered",
      order: ["hero", "services", "about", "stats", "process", "finished", "beforeAfter", "progress", "faq", "testimonials", "cta", "contact"],
    },
  },

  // 411 Basalt: volcanic slate dark with brass hardware, sadu bands, square industrial buttons and zigzag dividers.
  {
    code: "411",
    category: "ceramic",
    name: { ar: "البازلت", en: "Basalt" },
    description: { ar: "إردوازي بركاني داكن مع نحاس أصفر وخطوط سدو", en: "Dark volcanic slate with brass hardware and sadu bands" },
    tokens: {
      primary: "#c9a227",
      primaryFg: "#14130f",
      secondary: "#0f1216",
      secondaryFg: "#e6e8eb",
      accent: "#9fb3c8",
      accentFg: "#0f1216",
      bg: "#121517",
      surface: "#1a1e22",
      surface2: "#22272c",
      text: "#ecedee",
      muted: "#98a0a8",
      border: "#2f353b",
      headingFont: "notoKufi",
      bodyFont: "mada",
      radius: "sm",
      pattern: "sadu",
      mode: "dark",
      buttonStyle: "square",
      divider: "zigzag",
    },
    layout: {
      nav: "centered",
      hero: "stacked",
      services: "iconrow",
      about: "editorial",
      stats: "band",
      process: "timeline",
      finished: "grid",
      beforeAfter: "sidebyside",
      progress: "timeline",
      testimonials: "carousel",
      faq: "twocol",
      cta: "band",
      contact: "map",
      footer: "big",
    },
  },

  // 412 Coral: deep Gulf-night ocean with living coral and aqua, wave ripples, glowing buttons and xl soft corners.
  {
    code: "412",
    category: "ceramic",
    name: { ar: "المرجان", en: "Coral" },
    description: { ar: "أعماق البحر الليلية مع مرجاني حي وأمواج فيروزية", en: "Deep night ocean with living coral and aqua wave ripples" },
    tokens: {
      primary: "#ff7a5c",
      primaryFg: "#1a0f0c",
      secondary: "#05141f",
      secondaryFg: "#dbeefb",
      accent: "#4fd1c5",
      accentFg: "#06201f",
      bg: "#07111a",
      surface: "#0c1a26",
      surface2: "#122435",
      text: "#e6f1f8",
      muted: "#8fa5b8",
      border: "#1d3347",
      headingFont: "zain",
      bodyFont: "tajawal",
      radius: "xl",
      pattern: "waves",
      mode: "dark",
      buttonStyle: "glow",
      divider: "wave",
    },
    layout: {
      nav: "minimal",
      hero: "split",
      services: "grid",
      about: "split",
      stats: "cards",
      process: "numbers",
      finished: "masonry",
      beforeAfter: "tabs",
      progress: "filmstrip",
      testimonials: "quotewall",
      faq: "cards",
      cta: "split",
      contact: "inline",
      footer: "minimal",
      order: ["hero", "services", "finished", "beforeAfter", "about", "stats", "progress", "process", "testimonials", "cta", "faq", "contact"],
    },
  },

  // 413 Calacatta: gallery-white slab with charcoal type and a single gold vein, no pattern, fullscreen photographic hero.
  {
    code: "413",
    category: "ceramic",
    name: { ar: "الكالاكاتا", en: "Calacatta" },
    description: { ar: "أبيض معرضي نقي مع فحمي وعرق ذهبي واحد", en: "Pure gallery white with charcoal and a single gold vein" },
    tokens: {
      primary: "#1f2326",
      primaryFg: "#ffffff",
      secondary: "#111315",
      secondaryFg: "#f5f4f1",
      accent: "#b8963e",
      accentFg: "#1a1508",
      bg: "#ffffff",
      surface: "#f8f8f6",
      surface2: "#efeeea",
      text: "#1f2326",
      muted: "#6b6f73",
      border: "#e1e1dc",
      headingFont: "cairo",
      bodyFont: "almarai",
      radius: "none",
      pattern: "none",
      mode: "light",
      buttonStyle: "square",
      divider: "none",
    },
    layout: {
      nav: "transparent",
      hero: "fullscreen",
      services: "zigzag",
      about: "quote",
      stats: "inline",
      process: "steps",
      finished: "filmstrip",
      beforeAfter: "slider",
      progress: "slideshow",
      testimonials: "single",
      faq: "accordion",
      cta: "minimal",
      contact: "split",
      footer: "columns",
    },
  },

  // 414 Mosaic: playful tesserae of indigo, plum and saffron on lilac-white, dotted grout texture and fully rounded chips.
  {
    code: "414",
    category: "ceramic",
    name: { ar: "الفسيفساء", en: "Mosaic" },
    description: { ar: "فسيفساء مرحة بالنيلي والبرقوقي والزعفراني", en: "Playful mosaic of indigo, plum and saffron tesserae" },
    tokens: {
      primary: "#4338ca",
      primaryFg: "#ffffff",
      secondary: "#2e1065",
      secondaryFg: "#f3e8ff",
      accent: "#f59e0b",
      accentFg: "#1c1917",
      bg: "#fbfaff",
      surface: "#ffffff",
      surface2: "#eeedfa",
      text: "#1e1b3a",
      muted: "#6a6785",
      border: "#dedcf0",
      headingFont: "alexandria",
      bodyFont: "readex",
      radius: "full",
      pattern: "dots",
      mode: "light",
      buttonStyle: "pill",
      divider: "wave",
    },
    layout: {
      nav: "classic",
      hero: "centered",
      services: "carousel",
      about: "cards",
      stats: "circles",
      process: "cards",
      finished: "bento",
      beforeAfter: "hover",
      progress: "stepper",
      testimonials: "cards",
      faq: "twocol",
      cta: "card",
      contact: "cards",
      footer: "centered",
      order: ["hero", "about", "services", "finished", "stats", "process", "beforeAfter", "progress", "faq", "testimonials", "cta", "contact"],
    },
  },

  // 415 Clay: ochre kiln clay on sand with basalt-dark bands, hex tile texture, chunky Baloo headings and diagonal cuts.
  {
    code: "415",
    category: "ceramic",
    name: { ar: "الطين", en: "Clay" },
    description: { ar: "طين مغرة دافئ على رمل مع أشرطة بازلتية داكنة", en: "Warm ochre clay on sand with dark basalt bands" },
    tokens: {
      primary: "#9a5b1a",
      primaryFg: "#ffffff",
      secondary: "#26282a",
      secondaryFg: "#f4efe6",
      accent: "#e3c08d",
      accentFg: "#2b1d0e",
      bg: "#f8f3ea",
      surface: "#fffcf6",
      surface2: "#efe6d7",
      text: "#2b2420",
      muted: "#756a5f",
      border: "#e3d9c8",
      headingFont: "baloo",
      bodyFont: "vazirmatn",
      radius: "lg",
      pattern: "hex",
      mode: "light",
      buttonStyle: "solid",
      divider: "diagonal",
    },
    layout: {
      nav: "split",
      hero: "diagonal",
      services: "bento",
      about: "band",
      stats: "band",
      process: "timeline",
      finished: "grid",
      beforeAfter: "sidebyside",
      progress: "timeline",
      testimonials: "carousel",
      faq: "cards",
      cta: "band",
      contact: "map",
      footer: "big",
    },
  },
];
