import type { TemplateDef } from "../types";

/**
 * Gypsum board decor (ديكور جبس بورد) — 15 distinct premium designs, codes 101..115.
 * Layout slots hero/nav/services follow the platform rotation (offset 0):
 *   hero = HEROES[i % 10], nav = NAVS[(2i) % 7], services = SERVICES[(3i) % 7].
 * Four templates are dark mode (102, 106, 109, 113); the rest are light.
 */
export const GYPSUM_TEMPLATES: TemplateDef[] = [
  // 101 — Al Deera: ivory ground, deep bronze-gold primary and a Sadu band; the classic Kuwaiti heritage look.
  {
    code: "101",
    category: "gypsum",
    name: { ar: "الديرة", en: "Al Deera" },
    description: { ar: "أبيض عاجي ولمسات ذهبية برونزية مع نقوش السدو بروح الديرة الأصيلة", en: "Ivory and bronze gold with Sadu motifs, a timeless Kuwaiti heritage feel." },
    tokens: {
      primary: "#8a6420",
      primaryFg: "#ffffff",
      secondary: "#1c1710",
      secondaryFg: "#f7f1e3",
      accent: "#c9a24a",
      accentFg: "#1c1710",
      bg: "#fffdf8",
      surface: "#faf5ea",
      surface2: "#f2eadb",
      text: "#1f1a12",
      muted: "#6b6152",
      border: "#e6dcc6",
      headingFont: "cairo",
      bodyFont: "tajawal",
      radius: "sm",
      pattern: "sadu",
      mode: "light",
      buttonStyle: "solid",
      divider: "none",
    },
    layout: {
      nav: "classic",
      hero: "split",
      services: "grid",
      about: "split",
      stats: "band",
      process: "steps",
      finished: "grid",
      beforeAfter: "slider",
      progress: "slideshow",
      testimonials: "cards",
      faq: "accordion",
      cta: "band",
      contact: "split",
      footer: "columns",
    },
  },

  // 102 — Al Mirqab: charcoal dark with antique brass, razor-sharp square geometry and diagonal cuts.
  {
    code: "102",
    category: "gypsum",
    name: { ar: "المرقاب", en: "Al Mirqab" },
    description: { ar: "فحمي داكن ونحاس عتيق بخطوط حادة وهندسة إسلامية دقيقة", en: "Charcoal dark with antique brass and crisp Islamic geometry." },
    tokens: {
      primary: "#b08d57",
      primaryFg: "#17130c",
      secondary: "#0e0e10",
      secondaryFg: "#f4efe6",
      accent: "#e5c07b",
      accentFg: "#1a1610",
      bg: "#121212",
      surface: "#1a1a1c",
      surface2: "#222226",
      text: "#f2ede3",
      muted: "#a09a8e",
      border: "#2e2e33",
      headingFont: "changa",
      bodyFont: "almarai",
      radius: "none",
      pattern: "geometric",
      mode: "dark",
      buttonStyle: "square",
      divider: "diagonal",
    },
    layout: {
      nav: "split",
      hero: "fullscreen",
      services: "zigzag",
      about: "editorial",
      stats: "inline",
      process: "numbers",
      finished: "masonry",
      beforeAfter: "hover",
      progress: "filmstrip",
      testimonials: "single",
      faq: "twocol",
      cta: "minimal",
      contact: "inline",
      footer: "minimal",
      order: ["hero", "stats", "services", "finished", "beforeAfter", "about", "process", "progress", "testimonials", "cta", "faq", "contact"],
    },
  },

  // 103 — Al Nakheel: calm sage and soft cream, fully rounded pill shapes and flowing arabesque.
  {
    code: "103",
    category: "gypsum",
    name: { ar: "النخيل", en: "Al Nakheel" },
    description: { ar: "أخضر مريمي هادئ وكريمي ناعم بأشكال دائرية مريحة", en: "Calm sage and soft cream with gentle, fully rounded forms." },
    tokens: {
      primary: "#55704f",
      primaryFg: "#ffffff",
      secondary: "#22301f",
      secondaryFg: "#f3f5ee",
      accent: "#d9b96a",
      accentFg: "#22301f",
      bg: "#fbfaf5",
      surface: "#f3f4ec",
      surface2: "#e9ede1",
      text: "#1f261c",
      muted: "#5f6958",
      border: "#d9dfd0",
      headingFont: "elMessiri",
      bodyFont: "readex",
      radius: "full",
      pattern: "arabesque",
      mode: "light",
      buttonStyle: "pill",
      divider: "curve",
    },
    layout: {
      nav: "pill",
      hero: "centered",
      services: "carousel",
      about: "band",
      stats: "circles",
      process: "cards",
      finished: "carousel",
      beforeAfter: "sidebyside",
      progress: "stepper",
      testimonials: "carousel",
      faq: "cards",
      cta: "card",
      contact: "cards",
      footer: "centered",
    },
  },

  // 104 — Al Bahar: deep navy and sandy gold with wave dividers; the dhow-and-sea mood.
  {
    code: "104",
    category: "gypsum",
    name: { ar: "البحر", en: "Al Bahar" },
    description: { ar: "كحلي عميق ورمال ذهبية بإيقاع أمواج الخليج", en: "Deep navy and sandy gold with the rhythm of Gulf waves." },
    tokens: {
      primary: "#14365c",
      primaryFg: "#ffffff",
      secondary: "#0a1f3a",
      secondaryFg: "#eef3f8",
      accent: "#e0b567",
      accentFg: "#0a1f3a",
      bg: "#ffffff",
      surface: "#f4f6f9",
      surface2: "#e9eef4",
      text: "#0f1c2e",
      muted: "#5a6b80",
      border: "#d8e0ea",
      headingFont: "notoKufi",
      bodyFont: "ibmPlex",
      radius: "md",
      pattern: "waves",
      mode: "light",
      buttonStyle: "solid",
      divider: "wave",
    },
    layout: {
      nav: "boxed",
      hero: "diagonal",
      services: "bento",
      about: "cards",
      stats: "cards",
      process: "timeline",
      finished: "bento",
      beforeAfter: "tabs",
      progress: "timeline",
      testimonials: "quotewall",
      faq: "accordion",
      cta: "split",
      contact: "map",
      footer: "big",
      order: ["hero", "services", "about", "stats", "process", "finished", "beforeAfter", "progress", "testimonials", "cta", "faq", "contact"],
    },
  },

  // 105 — Al Lulu: pearl white and teal with a soft golden glow; dotted, luminous and airy.
  {
    code: "105",
    category: "gypsum",
    name: { ar: "اللؤلؤ", en: "Al Lulu" },
    description: { ar: "أبيض لؤلؤي وتركوازي مع توهج ذهبي ناعم", en: "Pearl white and teal with a soft golden glow." },
    tokens: {
      primary: "#0e7c7b",
      primaryFg: "#ffffff",
      secondary: "#0b3b3c",
      secondaryFg: "#eafaf8",
      accent: "#e8c56a",
      accentFg: "#14302f",
      bg: "#fdfdfc",
      surface: "#f5f8f7",
      surface2: "#eaf1ef",
      text: "#10201e",
      muted: "#5d6f6c",
      border: "#d8e3e0",
      headingFont: "alexandria",
      bodyFont: "notoSans",
      radius: "lg",
      pattern: "dots",
      mode: "light",
      buttonStyle: "glow",
      divider: "arch",
    },
    layout: {
      nav: "centered",
      hero: "cards",
      services: "tabs",
      about: "editorial",
      stats: "circles",
      process: "steps",
      finished: "filmstrip",
      beforeAfter: "slider",
      progress: "slideshow",
      testimonials: "cards",
      faq: "twocol",
      cta: "card",
      contact: "cards",
      footer: "columns",
    },
  },

  // 106 — Al Fanar: midnight-navy dark with warm amber and a sky-blue lighthouse beam under a starry pattern.
  {
    code: "106",
    category: "gypsum",
    name: { ar: "الفنار", en: "Al Fanar" },
    description: { ar: "ليل كحلي داكن مع كهرمان دافئ وشعاع سماوي", en: "Midnight dark with warm amber and a sky-blue beam." },
    tokens: {
      primary: "#e9a23b",
      primaryFg: "#1a1206",
      secondary: "#0b1220",
      secondaryFg: "#eef2f8",
      accent: "#6ec1e4",
      accentFg: "#0b1220",
      bg: "#0b1220",
      surface: "#111a2c",
      surface2: "#182238",
      text: "#eef2f8",
      muted: "#93a0b8",
      border: "#24304a",
      headingFont: "lalezar",
      bodyFont: "vazirmatn",
      radius: "xl",
      pattern: "stars",
      mode: "dark",
      buttonStyle: "glow",
      divider: "none",
    },
    layout: {
      nav: "minimal",
      hero: "video",
      services: "list",
      about: "quote",
      stats: "inline",
      process: "timeline",
      finished: "filmstrip",
      beforeAfter: "hover",
      progress: "stepper",
      testimonials: "single",
      faq: "cards",
      cta: "minimal",
      contact: "inline",
      footer: "minimal",
      order: ["hero", "stats", "services", "finished", "progress", "beforeAfter", "about", "process", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 107 — Al Mashrabiya: warm terracotta and cream in a magazine-editorial layout with lattice motifs and underline buttons.
  {
    code: "107",
    category: "gypsum",
    name: { ar: "المشربية", en: "Al Mashrabiya" },
    description: { ar: "طيني دافئ وكريمي بأسلوب مجلة أنيق ونقش المشربية", en: "Warm terracotta and cream in an elegant editorial style with lattice motifs." },
    tokens: {
      primary: "#b5532d",
      primaryFg: "#ffffff",
      secondary: "#3b2218",
      secondaryFg: "#f8efe6",
      accent: "#d9a566",
      accentFg: "#3b2218",
      bg: "#fdf8f2",
      surface: "#f7efe5",
      surface2: "#f0e4d4",
      text: "#2a1d16",
      muted: "#75635a",
      border: "#e6d6c4",
      headingFont: "amiri",
      bodyFont: "mada",
      radius: "none",
      pattern: "mashrabiya",
      mode: "light",
      buttonStyle: "underline",
      divider: "none",
    },
    layout: {
      nav: "transparent",
      hero: "editorial",
      services: "iconrow",
      about: "quote",
      stats: "inline",
      process: "numbers",
      finished: "masonry",
      beforeAfter: "sidebyside",
      progress: "timeline",
      testimonials: "quotewall",
      faq: "twocol",
      cta: "minimal",
      contact: "split",
      footer: "centered",
    },
  },

  // 108 — Al Ghuroob: deep plum and ivory warmed by sunset orange; diamond lattice with curved dividers.
  {
    code: "108",
    category: "gypsum",
    name: { ar: "الغروب", en: "Al Ghuroob" },
    description: { ar: "بنفسجي غامق وعاجي مع دفء برتقالي الغروب", en: "Deep plum and ivory warmed by sunset orange." },
    tokens: {
      primary: "#6b2d5c",
      primaryFg: "#ffffff",
      secondary: "#2a1024",
      secondaryFg: "#f9eef5",
      accent: "#e58f5a",
      accentFg: "#2a1024",
      bg: "#fffbfa",
      surface: "#faf3f5",
      surface2: "#f3e8ec",
      text: "#24141f",
      muted: "#6f5c69",
      border: "#e7d9df",
      headingFont: "marhey",
      bodyFont: "rubik",
      radius: "lg",
      pattern: "diamonds",
      mode: "light",
      buttonStyle: "pill",
      divider: "curve",
    },
    layout: {
      nav: "classic",
      hero: "gallery",
      services: "grid",
      about: "split",
      stats: "cards",
      process: "cards",
      finished: "grid",
      beforeAfter: "tabs",
      progress: "filmstrip",
      testimonials: "carousel",
      faq: "accordion",
      cta: "band",
      contact: "map",
      footer: "big",
      order: ["hero", "finished", "about", "services", "stats", "beforeAfter", "progress", "process", "testimonials", "cta", "faq", "contact"],
    },
  },

  // 109 — Al Dana: deep forest dark with luxurious gold, arched hero, hex tiling and outlined buttons.
  {
    code: "109",
    category: "gypsum",
    name: { ar: "الدانة", en: "Al Dana" },
    description: { ar: "أخضر غابي داكن وذهب فاخر بأقواس أنيقة", en: "Deep forest dark with luxurious gold and elegant arches." },
    tokens: {
      primary: "#c49b1f",
      primaryFg: "#101a12",
      secondary: "#0a1f14",
      secondaryFg: "#eef5ef",
      accent: "#7fb593",
      accentFg: "#0a1f14",
      bg: "#0e2418",
      surface: "#133021",
      surface2: "#183a29",
      text: "#eef5ef",
      muted: "#9fb8a8",
      border: "#244a36",
      headingFont: "reemKufi",
      bodyFont: "harmattan",
      radius: "full",
      pattern: "hex",
      mode: "dark",
      buttonStyle: "outline",
      divider: "arch",
    },
    layout: {
      nav: "split",
      hero: "arch",
      services: "zigzag",
      about: "quote",
      stats: "circles",
      process: "timeline",
      finished: "carousel",
      beforeAfter: "slider",
      progress: "stepper",
      testimonials: "single",
      faq: "cards",
      cta: "split",
      contact: "cards",
      footer: "centered",
    },
  },

  // 110 — Al Rimal: desert sand and burnt umber, zigzag dune dividers and calligraphic headings.
  {
    code: "110",
    category: "gypsum",
    name: { ar: "الرمال", en: "Al Rimal" },
    description: { ar: "رمال الصحراء وبني محروق بإيقاع الكثبان", en: "Desert sand and burnt umber with the rhythm of dunes." },
    tokens: {
      primary: "#9a5b2f",
      primaryFg: "#ffffff",
      secondary: "#3a2a1c",
      secondaryFg: "#f8f1e6",
      accent: "#e3c28a",
      accentFg: "#3a2a1c",
      bg: "#faf5ec",
      surface: "#f4ecdd",
      surface2: "#ece1cc",
      text: "#2b2118",
      muted: "#6d5e52",
      border: "#e0d3bd",
      headingFont: "arefRuqaa",
      bodyFont: "notoNaskh",
      radius: "xl",
      pattern: "lines",
      mode: "light",
      buttonStyle: "solid",
      divider: "zigzag",
    },
    layout: {
      nav: "pill",
      hero: "stacked",
      services: "carousel",
      about: "band",
      stats: "band",
      process: "steps",
      finished: "bento",
      beforeAfter: "hover",
      progress: "timeline",
      testimonials: "cards",
      faq: "accordion",
      cta: "card",
      contact: "split",
      footer: "columns",
      order: ["hero", "about", "stats", "services", "process", "finished", "beforeAfter", "progress", "cta", "testimonials", "faq", "contact"],
    },
  },

  // 111 — Al Naqaa: pure black-and-white minimalism with a bold red accent; no radius, no pattern, square buttons.
  {
    code: "111",
    category: "gypsum",
    name: { ar: "النقاء", en: "Al Naqaa" },
    description: { ar: "أسود وأبيض بسيط جداً مع لمسة حمراء جريئة", en: "Pure black-and-white minimalism with a bold red accent." },
    tokens: {
      primary: "#111111",
      primaryFg: "#ffffff",
      secondary: "#000000",
      secondaryFg: "#ffffff",
      accent: "#d62828",
      accentFg: "#ffffff",
      bg: "#ffffff",
      surface: "#f6f6f6",
      surface2: "#ececec",
      text: "#111111",
      muted: "#666666",
      border: "#dddddd",
      headingFont: "zain",
      bodyFont: "ibmPlex",
      radius: "none",
      pattern: "none",
      mode: "light",
      buttonStyle: "square",
      divider: "none",
    },
    layout: {
      nav: "boxed",
      hero: "split",
      services: "bento",
      about: "editorial",
      stats: "inline",
      process: "numbers",
      finished: "masonry",
      beforeAfter: "sidebyside",
      progress: "filmstrip",
      testimonials: "quotewall",
      faq: "twocol",
      cta: "minimal",
      contact: "inline",
      footer: "minimal",
    },
  },

  // 112 — Al Fairuz: fresh turquoise and crisp white with lively coral; rounded, wave-cut and playful.
  {
    code: "112",
    category: "gypsum",
    name: { ar: "الفيروز", en: "Al Fairuz" },
    description: { ar: "فيروزي منعش وأبيض ناصع مع مرجاني حيوي", en: "Fresh turquoise and crisp white with lively coral." },
    tokens: {
      primary: "#0b7285",
      primaryFg: "#ffffff",
      secondary: "#073b45",
      secondaryFg: "#e6f7fa",
      accent: "#f2705b",
      accentFg: "#1a0f0c",
      bg: "#ffffff",
      surface: "#f2fafb",
      surface2: "#e3f3f5",
      text: "#0b2226",
      muted: "#557077",
      border: "#cfe4e8",
      headingFont: "baloo",
      bodyFont: "tajawal",
      radius: "xl",
      pattern: "waves",
      mode: "light",
      buttonStyle: "pill",
      divider: "wave",
    },
    layout: {
      nav: "centered",
      hero: "fullscreen",
      services: "tabs",
      about: "cards",
      stats: "cards",
      process: "cards",
      finished: "carousel",
      beforeAfter: "slider",
      progress: "slideshow",
      testimonials: "carousel",
      faq: "cards",
      cta: "band",
      contact: "map",
      footer: "big",
      order: ["hero", "services", "stats", "about", "finished", "beforeAfter", "progress", "process", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 113 — Al Sadu: warm black with Sadu red and orange gold, zigzag weaving rhythm and outlined buttons.
  {
    code: "113",
    category: "gypsum",
    name: { ar: "السدو", en: "Al Sadu" },
    description: { ar: "أسود دافئ وأحمر السدو وذهبي برتقالي بنسيج تراثي", en: "Warm black with Sadu red and orange gold in a woven heritage feel." },
    tokens: {
      primary: "#bf3f2b",
      primaryFg: "#ffffff",
      secondary: "#0f0b0c",
      secondaryFg: "#f5ece0",
      accent: "#e8b04b",
      accentFg: "#1a1210",
      bg: "#171213",
      surface: "#1f191a",
      surface2: "#2a2223",
      text: "#f5ece0",
      muted: "#a89c93",
      border: "#382e30",
      headingFont: "rakkas",
      bodyFont: "almarai",
      radius: "sm",
      pattern: "sadu",
      mode: "dark",
      buttonStyle: "outline",
      divider: "zigzag",
    },
    layout: {
      nav: "minimal",
      hero: "centered",
      services: "list",
      about: "quote",
      stats: "band",
      process: "timeline",
      finished: "filmstrip",
      beforeAfter: "tabs",
      progress: "timeline",
      testimonials: "single",
      faq: "accordion",
      cta: "split",
      contact: "split",
      footer: "centered",
    },
  },

  // 114 — Al Sabah: airy slate blue and warm white with a morning brass touch; light geometric headings.
  {
    code: "114",
    category: "gypsum",
    name: { ar: "الصباح", en: "Al Sabah" },
    description: { ar: "أزرق رمادي هادئ وأبيض دافئ بلمسة نحاسية صباحية", en: "Airy slate blue and warm white with a morning brass touch." },
    tokens: {
      primary: "#3f5f7a",
      primaryFg: "#ffffff",
      secondary: "#1e2f3f",
      secondaryFg: "#eef3f7",
      accent: "#c99a5b",
      accentFg: "#1e2f3f",
      bg: "#fbfbf9",
      surface: "#f3f5f6",
      surface2: "#e8edf0",
      text: "#1a2733",
      muted: "#5a6975",
      border: "#d7dfe5",
      headingFont: "readex",
      bodyFont: "vazirmatn",
      radius: "md",
      pattern: "geometric",
      mode: "light",
      buttonStyle: "outline",
      divider: "diagonal",
    },
    layout: {
      nav: "transparent",
      hero: "diagonal",
      services: "iconrow",
      about: "split",
      stats: "circles",
      process: "steps",
      finished: "grid",
      beforeAfter: "hover",
      progress: "stepper",
      testimonials: "cards",
      faq: "twocol",
      cta: "card",
      contact: "cards",
      footer: "columns",
      order: ["hero", "stats", "about", "services", "process", "finished", "beforeAfter", "progress", "testimonials", "cta", "faq", "contact"],
    },
  },

  // 115 — Al Aqeeq: deep oxblood and luxurious champagne with mashrabiya lattice, glowing buttons and arch dividers.
  {
    code: "115",
    category: "gypsum",
    name: { ar: "العقيق", en: "Al Aqeeq" },
    description: { ar: "عنابي عميق وشمبانيا فاخرة بنقش المشربية", en: "Deep oxblood and luxurious champagne with mashrabiya lattice." },
    tokens: {
      primary: "#7a1f2b",
      primaryFg: "#ffffff",
      secondary: "#2a0e13",
      secondaryFg: "#f9efe9",
      accent: "#d8b56f",
      accentFg: "#2a0e13",
      bg: "#fffcf9",
      surface: "#f9f3ee",
      surface2: "#f2e9e2",
      text: "#26161a",
      muted: "#715b60",
      border: "#e7d9d6",
      headingFont: "kufam",
      bodyFont: "notoSans",
      radius: "lg",
      pattern: "mashrabiya",
      mode: "light",
      buttonStyle: "glow",
      divider: "arch",
    },
    layout: {
      nav: "classic",
      hero: "cards",
      services: "grid",
      about: "band",
      stats: "cards",
      process: "numbers",
      finished: "bento",
      beforeAfter: "sidebyside",
      progress: "slideshow",
      testimonials: "quotewall",
      faq: "accordion",
      cta: "band",
      contact: "map",
      footer: "big",
    },
  },
];
