import type { TemplateDef } from "../types";

/**
 * Partition (بارتيشن) templates 301-315: office partitions, glass walls, movable walls, acoustic panels.
 * Each entry is a distinct premium look (palette, type, shape language, motif and section composition)
 * with a Kuwaiti / Gulf flavour. Hero, nav and services variants follow the category rotation (offset 6).
 */
export const PARTITION_TEMPLATES: TemplateDef[] = [
  // 301 Space: airy violet editorial with a mint highlight and a hex lattice, rounded pill buttons — open-plan, modern.
  {
    code: "301",
    category: "partition",
    name: { ar: "الفضاء", en: "Space" },
    description: { ar: "بنفسجي هادئ مع لمسة نعناعية وشبكة سداسية تفتح المساحة", en: "Calm violet with a mint highlight and a hex lattice that opens up the space" },
    tokens: {
      primary: "#6d28d9",
      primaryFg: "#ffffff",
      secondary: "#1e1b4b",
      secondaryFg: "#ede9fe",
      accent: "#6ee7b7",
      accentFg: "#064e3b",
      bg: "#ffffff",
      surface: "#faf9ff",
      surface2: "#f1eefc",
      text: "#1a1730",
      muted: "#5e5a7a",
      border: "#e4e0f3",
      headingFont: "elMessiri",
      bodyFont: "ibmPlex",
      radius: "lg",
      pattern: "hex",
      mode: "light",
      buttonStyle: "pill",
      divider: "curve",
    },
    layout: {
      nav: "boxed",
      hero: "editorial",
      services: "carousel",
      about: "editorial",
      stats: "inline",
      process: "numbers",
      finished: "masonry",
      beforeAfter: "slider",
      progress: "slideshow",
      testimonials: "quotewall",
      faq: "accordion",
      cta: "band",
      contact: "split",
      footer: "columns",
      order: ["hero", "services", "about", "finished", "stats", "beforeAfter", "progress", "process", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 302 The Office: crisp slate corporate grid with a lime punch, square corners and fine diagonal pinstripes.
  {
    code: "302",
    category: "partition",
    name: { ar: "المكتب", en: "The Office" },
    description: { ar: "رمادي أردوازي مؤسسي بحواف حادة ولمسة ليمونية نابضة", en: "Corporate slate with sharp edges and a punchy lime highlight" },
    tokens: {
      primary: "#36455c",
      primaryFg: "#ffffff",
      secondary: "#0f172a",
      secondaryFg: "#e2e8f0",
      accent: "#a3e635",
      accentFg: "#1a2e05",
      bg: "#f8fafc",
      surface: "#ffffff",
      surface2: "#e9eef4",
      text: "#0f172a",
      muted: "#55606e",
      border: "#d5dde6",
      headingFont: "sora",
      bodyFont: "tajawal",
      radius: "sm",
      pattern: "lines",
      mode: "light",
      buttonStyle: "square",
      divider: "none",
    },
    layout: {
      nav: "centered",
      hero: "gallery",
      services: "bento",
      about: "cards",
      stats: "cards",
      process: "steps",
      finished: "bento",
      beforeAfter: "sidebyside",
      progress: "stepper",
      testimonials: "cards",
      faq: "twocol",
      cta: "card",
      contact: "cards",
      footer: "big",
    },
  },

  // 303 Transparency: frosted-glass steel blue and ice, soft arches and generous radius — glass walls and daylight.
  {
    code: "303",
    category: "partition",
    name: { ar: "الشفافية", en: "Transparency" },
    description: { ar: "أزرق فولاذي وجليدي بأقواس ناعمة يوحي بالزجاج والضوء", en: "Steel blue and ice with soft arches that evoke glass and daylight" },
    tokens: {
      primary: "#2b5f7e",
      primaryFg: "#ffffff",
      secondary: "#10283a",
      secondaryFg: "#e6f4fb",
      accent: "#bde8f7",
      accentFg: "#0b3448",
      bg: "#f4f9fc",
      surface: "#ffffff",
      surface2: "#e6f0f6",
      text: "#0f2233",
      muted: "#536a7a",
      border: "#d3e2ec",
      headingFont: "manrope",
      bodyFont: "readex",
      radius: "xl",
      pattern: "dots",
      mode: "light",
      buttonStyle: "outline",
      divider: "arch",
    },
    layout: {
      nav: "minimal",
      hero: "arch",
      services: "tabs",
      about: "quote",
      stats: "circles",
      process: "timeline",
      finished: "carousel",
      beforeAfter: "hover",
      progress: "timeline",
      testimonials: "single",
      faq: "cards",
      cta: "minimal",
      contact: "map",
      footer: "minimal",
      order: ["hero", "about", "finished", "services", "beforeAfter", "stats", "process", "progress", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 304 Mashrabiya: brass on porcelain with walnut bands, a mashrabiya lattice, Ruqaa headings and zero radius — heritage screens.
  {
    code: "304",
    category: "partition",
    name: { ar: "النحاس", en: "Brass" },
    description: { ar: "نحاس على بورسلين مع زخرفة مشربية وخط رقعة تراثي", en: "Brass on porcelain with a mashrabiya lattice and heritage Ruqaa headings" },
    tokens: {
      primary: "#b8860b",
      primaryFg: "#1a1200",
      secondary: "#3b2a1a",
      secondaryFg: "#f6ecd9",
      accent: "#8b2e2e",
      accentFg: "#fff7ed",
      bg: "#fbf7ef",
      surface: "#ffffff",
      surface2: "#f3ebdc",
      text: "#2a1f14",
      muted: "#6b5d4c",
      border: "#e6dac4",
      headingFont: "arefRuqaa",
      bodyFont: "notoNaskh",
      radius: "none",
      pattern: "mashrabiya",
      mode: "light",
      buttonStyle: "underline",
      divider: "none",
    },
    layout: {
      nav: "transparent",
      hero: "stacked",
      services: "list",
      about: "band",
      stats: "band",
      process: "cards",
      finished: "filmstrip",
      beforeAfter: "tabs",
      progress: "filmstrip",
      testimonials: "carousel",
      faq: "accordion",
      cta: "split",
      contact: "inline",
      footer: "centered",
    },
  },

  // 305 The Screen: ink black with a coral flash, diamond grid and diagonal cuts — bold, graphic, high contrast.
  {
    code: "305",
    category: "partition",
    name: { ar: "الحاجز", en: "The Screen" },
    description: { ar: "أسود حبري مع ومضة مرجانية وقطع مائلة جريئة", en: "Ink black with a coral flash and bold diagonal cuts" },
    tokens: {
      primary: "#111827",
      primaryFg: "#ffffff",
      secondary: "#1e293b",
      secondaryFg: "#f3f4f6",
      accent: "#fb7185",
      accentFg: "#4c0519",
      bg: "#ffffff",
      surface: "#f9fafb",
      surface2: "#f1f3f6",
      text: "#111827",
      muted: "#5a6373",
      border: "#e2e6ec",
      headingFont: "kufam",
      bodyFont: "rubik",
      radius: "md",
      pattern: "diamonds",
      mode: "light",
      buttonStyle: "solid",
      divider: "diagonal",
    },
    layout: {
      nav: "classic",
      hero: "split",
      services: "iconrow",
      about: "split",
      stats: "band",
      process: "steps",
      finished: "grid",
      beforeAfter: "slider",
      progress: "stepper",
      testimonials: "cards",
      faq: "twocol",
      cta: "band",
      contact: "split",
      footer: "columns",
      order: ["hero", "services", "stats", "about", "finished", "process", "beforeAfter", "progress", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 306 The System: dark graphite with electric cyan and an amber warning accent, geometric star grid, glowing buttons — modular and technical.
  {
    code: "306",
    category: "partition",
    name: { ar: "النظام", en: "The System" },
    description: { ar: "جرافيت داكن مع سماوي كهربائي وشبكة هندسية تقنية", en: "Dark graphite with electric cyan and a technical geometric grid" },
    tokens: {
      primary: "#22d3ee",
      primaryFg: "#062a30",
      secondary: "#0f1216",
      secondaryFg: "#e5e7eb",
      accent: "#fbbf24",
      accentFg: "#2a1a00",
      bg: "#1b1f26",
      surface: "#232830",
      surface2: "#2b313b",
      text: "#eef2f7",
      muted: "#9aa4b2",
      border: "#343b47",
      headingFont: "changa",
      bodyFont: "vazirmatn",
      radius: "sm",
      pattern: "geometric",
      mode: "dark",
      buttonStyle: "glow",
      divider: "none",
    },
    layout: {
      nav: "split",
      hero: "fullscreen",
      services: "grid",
      about: "editorial",
      stats: "inline",
      process: "timeline",
      finished: "bento",
      beforeAfter: "hover",
      progress: "timeline",
      testimonials: "quotewall",
      faq: "cards",
      cta: "minimal",
      contact: "cards",
      footer: "big",
    },
  },

  // 307 Calm: deep teal with warm sand, fully rounded shapes, gentle waves — acoustic quiet and Gulf shoreline.
  {
    code: "307",
    category: "partition",
    name: { ar: "الهدوء", en: "Calm" },
    description: { ar: "أزرق مخضر عميق مع رمل دافئ وأشكال دائرية وأمواج لطيفة", en: "Deep teal with warm sand, rounded shapes and gentle waves" },
    tokens: {
      primary: "#0c6f78",
      primaryFg: "#ffffff",
      secondary: "#0a3d44",
      secondaryFg: "#e6f6f5",
      accent: "#e8d5a8",
      accentFg: "#3f2f10",
      bg: "#fbfaf6",
      surface: "#ffffff",
      surface2: "#f2eee2",
      text: "#132b2c",
      muted: "#5b6b6a",
      border: "#e3ddcc",
      headingFont: "alexandria",
      bodyFont: "almarai",
      radius: "full",
      pattern: "waves",
      mode: "light",
      buttonStyle: "pill",
      divider: "wave",
    },
    layout: {
      nav: "pill",
      hero: "centered",
      services: "zigzag",
      about: "quote",
      stats: "circles",
      process: "numbers",
      finished: "masonry",
      beforeAfter: "sidebyside",
      progress: "slideshow",
      testimonials: "single",
      faq: "accordion",
      cta: "card",
      contact: "map",
      footer: "centered",
      order: ["hero", "about", "services", "finished", "beforeAfter", "progress", "stats", "process", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 308 Flexibility: plum and peach with arabesque curls, zigzag dividers and playful Marhey headings — movable walls that bend.
  {
    code: "308",
    category: "partition",
    name: { ar: "المرونة", en: "Flexibility" },
    description: { ar: "برقوقي وخوخي مع أرابيسك مرح وفواصل متعرجة", en: "Plum and peach with playful arabesque curls and zigzag dividers" },
    tokens: {
      primary: "#6b1d5c",
      primaryFg: "#ffffff",
      secondary: "#2e0f2a",
      secondaryFg: "#fbe9f5",
      accent: "#ffb088",
      accentFg: "#4a1d05",
      bg: "#fffaf7",
      surface: "#ffffff",
      surface2: "#fbeee8",
      text: "#2a1526",
      muted: "#6e5a6a",
      border: "#f0dfe0",
      headingFont: "marhey",
      bodyFont: "mada",
      radius: "xl",
      pattern: "arabesque",
      mode: "light",
      buttonStyle: "pill",
      divider: "zigzag",
    },
    layout: {
      nav: "boxed",
      hero: "diagonal",
      services: "carousel",
      about: "cards",
      stats: "cards",
      process: "cards",
      finished: "carousel",
      beforeAfter: "tabs",
      progress: "filmstrip",
      testimonials: "carousel",
      faq: "twocol",
      cta: "split",
      contact: "inline",
      footer: "minimal",
    },
  },

  // 309 Crystal: pure white gallery with emerald, no pattern, Playfair serif headings and outline buttons — glass showroom minimalism.
  {
    code: "309",
    category: "partition",
    name: { ar: "البلور", en: "Crystal" },
    description: { ar: "أبيض نقي مع زمردي وخط سيريف راقٍ بلا زخارف", en: "Pure white with emerald and refined serif headings, no ornament" },
    tokens: {
      primary: "#047857",
      primaryFg: "#ffffff",
      secondary: "#04231c",
      secondaryFg: "#d1fae5",
      accent: "#34d399",
      accentFg: "#052e16",
      bg: "#ffffff",
      surface: "#fafcfb",
      surface2: "#eef5f1",
      text: "#0b1f18",
      muted: "#56695f",
      border: "#dbe7e0",
      headingFont: "playfair",
      bodyFont: "notoSans",
      radius: "sm",
      pattern: "none",
      mode: "light",
      buttonStyle: "outline",
      divider: "none",
    },
    layout: {
      nav: "centered",
      hero: "cards",
      services: "bento",
      about: "split",
      stats: "band",
      process: "steps",
      finished: "grid",
      beforeAfter: "slider",
      progress: "stepper",
      testimonials: "cards",
      faq: "cards",
      cta: "band",
      contact: "split",
      footer: "columns",
      order: ["hero", "finished", "about", "services", "stats", "beforeAfter", "progress", "process", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 310 Privacy: near-black with neon green, pinstripes and glowing buttons, cinematic video hero — private, secure spaces.
  {
    code: "310",
    category: "partition",
    name: { ar: "الخصوصية", en: "Privacy" },
    description: { ar: "أسود شبه كامل مع أخضر نيون وأزرار متوهجة بطابع سينمائي", en: "Near-black with neon green and glowing buttons in a cinematic mood" },
    tokens: {
      primary: "#39ff6b",
      primaryFg: "#03200a",
      secondary: "#0c2f1a",
      secondaryFg: "#dcfce7",
      accent: "#f5f5f5",
      accentFg: "#0b0b0b",
      bg: "#0b0b0b",
      surface: "#141414",
      surface2: "#1c1c1c",
      text: "#f2f2f2",
      muted: "#9a9a9a",
      border: "#2a2a2a",
      headingFont: "zain",
      bodyFont: "readex",
      radius: "md",
      pattern: "lines",
      mode: "dark",
      buttonStyle: "glow",
      divider: "diagonal",
    },
    layout: {
      nav: "minimal",
      hero: "video",
      services: "tabs",
      about: "band",
      stats: "inline",
      process: "numbers",
      finished: "filmstrip",
      beforeAfter: "hover",
      progress: "slideshow",
      testimonials: "single",
      faq: "accordion",
      cta: "minimal",
      contact: "cards",
      footer: "minimal",
    },
  },

  // 311 Elegance: charcoal with gold and champagne, Sadu weave, Amiri serif and underline buttons — executive suites, no radius.
  {
    code: "311",
    category: "partition",
    name: { ar: "الأناقة", en: "Elegance" },
    description: { ar: "فحمي مع ذهبي وشمبانيا ونقش السدو بخط أميري فاخر", en: "Charcoal with gold and champagne, a Sadu weave and luxurious Amiri type" },
    tokens: {
      primary: "#cfa62b",
      primaryFg: "#1a1405",
      secondary: "#101012",
      secondaryFg: "#f3ecd9",
      accent: "#e8d9b0",
      accentFg: "#2b2411",
      bg: "#1c1c1e",
      surface: "#242426",
      surface2: "#2c2c2f",
      text: "#f4efe4",
      muted: "#a8a196",
      border: "#3a3a3e",
      headingFont: "amiri",
      bodyFont: "harmattan",
      radius: "none",
      pattern: "sadu",
      mode: "dark",
      buttonStyle: "underline",
      divider: "none",
    },
    layout: {
      nav: "transparent",
      hero: "editorial",
      services: "list",
      about: "quote",
      stats: "circles",
      process: "timeline",
      finished: "masonry",
      beforeAfter: "sidebyside",
      progress: "timeline",
      testimonials: "quotewall",
      faq: "twocol",
      cta: "card",
      contact: "map",
      footer: "big",
      order: ["hero", "about", "finished", "services", "process", "stats", "beforeAfter", "progress", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 312 Clarity: sky blue and navy with a fine dot field and curved dividers, Cairo headings — bright daylight offices.
  {
    code: "312",
    category: "partition",
    name: { ar: "الوضوح", en: "Clarity" },
    description: { ar: "سماوي وكحلي مع نقاط دقيقة وفواصل منحنية مشرقة", en: "Sky blue and navy with a fine dot field and bright curved dividers" },
    tokens: {
      primary: "#0369a1",
      primaryFg: "#ffffff",
      secondary: "#1e3a8a",
      secondaryFg: "#dbeafe",
      accent: "#7dd3fc",
      accentFg: "#082f49",
      bg: "#ffffff",
      surface: "#f5f9fd",
      surface2: "#e8f1f9",
      text: "#0c1a2e",
      muted: "#526478",
      border: "#d6e2ee",
      headingFont: "cairo",
      bodyFont: "tajawal",
      radius: "md",
      pattern: "dots",
      mode: "light",
      buttonStyle: "solid",
      divider: "curve",
    },
    layout: {
      nav: "classic",
      hero: "gallery",
      services: "iconrow",
      about: "editorial",
      stats: "cards",
      process: "cards",
      finished: "bento",
      beforeAfter: "tabs",
      progress: "stepper",
      testimonials: "carousel",
      faq: "cards",
      cta: "split",
      contact: "inline",
      footer: "centered",
    },
  },

  // 313 Modernity: olive and cream with ochre, hex honeycomb, arch hero and Reem Kufi headings — warm contemporary workspace.
  {
    code: "313",
    category: "partition",
    name: { ar: "الحداثة", en: "Modernity" },
    description: { ar: "زيتوني وكريمي مع أوكر وخلية سداسية وخط كوفي معاصر", en: "Olive and cream with ochre, a honeycomb motif and contemporary Kufi type" },
    tokens: {
      primary: "#556b2f",
      primaryFg: "#ffffff",
      secondary: "#1f2a14",
      secondaryFg: "#f2f0e4",
      accent: "#d4a53a",
      accentFg: "#2a1f05",
      bg: "#fbf8ef",
      surface: "#ffffff",
      surface2: "#f2eedf",
      text: "#1e2415",
      muted: "#5f6553",
      border: "#e2ddca",
      headingFont: "reemKufi",
      bodyFont: "mada",
      radius: "lg",
      pattern: "hex",
      mode: "light",
      buttonStyle: "solid",
      divider: "arch",
    },
    layout: {
      nav: "split",
      hero: "arch",
      services: "grid",
      about: "band",
      stats: "band",
      process: "steps",
      finished: "carousel",
      beforeAfter: "slider",
      progress: "filmstrip",
      testimonials: "cards",
      faq: "accordion",
      cta: "band",
      contact: "split",
      footer: "columns",
      order: ["hero", "services", "about", "stats", "process", "finished", "beforeAfter", "progress", "testimonials", "faq", "cta", "contact"],
    },
  },

  // 314 Balance: terracotta and sage on warm white, geometric eight-point stars, wave dividers, Noto Kufi — earthy Gulf balance.
  {
    code: "314",
    category: "partition",
    name: { ar: "الميزان", en: "Balance" },
    description: { ar: "طيني وميرمية على أبيض دافئ مع نجوم هندسية خليجية", en: "Terracotta and sage on warm white with Gulf geometric stars" },
    tokens: {
      primary: "#b7410e",
      primaryFg: "#ffffff",
      secondary: "#3b1f14",
      secondaryFg: "#fbeee6",
      accent: "#b9cdb3",
      accentFg: "#1f2e1c",
      bg: "#fcfaf7",
      surface: "#ffffff",
      surface2: "#f1ece5",
      text: "#26201b",
      muted: "#6a615a",
      border: "#e5ddd3",
      headingFont: "notoKufi",
      bodyFont: "almarai",
      radius: "lg",
      pattern: "geometric",
      mode: "light",
      buttonStyle: "solid",
      divider: "wave",
    },
    layout: {
      nav: "pill",
      hero: "stacked",
      services: "zigzag",
      about: "cards",
      stats: "inline",
      process: "numbers",
      finished: "grid",
      beforeAfter: "hover",
      progress: "slideshow",
      testimonials: "single",
      faq: "twocol",
      cta: "minimal",
      contact: "cards",
      footer: "minimal",
    },
  },

  // 315 Horizon: midnight navy with turquoise and a sunset-sand accent, star field, full radius and glow — Kuwait skyline at dusk.
  {
    code: "315",
    category: "partition",
    name: { ar: "النجوم", en: "Starfield" },
    description: { ar: "كحلي منتصف الليل مع فيروزي ولمسة غروب رملية وحقل نجوم", en: "Midnight navy with turquoise, a sandy sunset accent and a star field" },
    tokens: {
      primary: "#2dd4bf",
      primaryFg: "#042f2e",
      secondary: "#050a1c",
      secondaryFg: "#e0f2fe",
      accent: "#f4a261",
      accentFg: "#3d1e02",
      bg: "#0b1437",
      surface: "#121c48",
      surface2: "#1a2557",
      text: "#eaf0ff",
      muted: "#9aa6cf",
      border: "#2a3566",
      headingFont: "lalezar",
      bodyFont: "vazirmatn",
      radius: "full",
      pattern: "stars",
      mode: "dark",
      buttonStyle: "glow",
      divider: "wave",
    },
    layout: {
      nav: "boxed",
      hero: "split",
      services: "carousel",
      about: "split",
      stats: "circles",
      process: "timeline",
      finished: "filmstrip",
      beforeAfter: "sidebyside",
      progress: "timeline",
      testimonials: "quotewall",
      faq: "cards",
      cta: "card",
      contact: "map",
      footer: "big",
      order: ["hero", "about", "services", "finished", "stats", "process", "beforeAfter", "progress", "testimonials", "faq", "cta", "contact"],
    },
  },
];
